### ISSUE TITLE
Support python3.9

### ISSUE THREAD

**Issue by alexanderankin** [alexanderankin/pyfpdf#8]
When installing with python3.9, the following error message occurs (private details omitted):

pillow also has a list of compatible versions to reference [here](https://pillow.readthedocs.io/en/stable/installation.html) so that's probably something to just update, the question is which one? I don't remember why the current version was chosen.

```sh
(39env) $USER@HOSTNAME:~$ pip install fpdf2
Collecting fpdf2
  Using cached fpdf2-2.0.5-py2.py3-none-any.whl (71 kB)
Collecting numpy
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Pillow<7.0,>=4
  Downloading Pillow-6.2.2.tar.gz (37.8 MB)
     |████████████████████████████████| 37.8 MB 6.2 MB/s 
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Building wheels for collected packages: numpy, Pillow, future
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.19.2-cp39-cp39-linux_x86_64.whl size=16980752 sha256=d916775dd4dd8eb16f3313270470bc0059de0dadcb5f8e1e51027f86d4ec060c
  Stored in directory: $HOME/.cache/pip/wheels/a3/17/dd/f2dba23a35bb6008732772ccfb13d3d0e537fbc6919ce6862b
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: $VIRTUALENV/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"'; __file__='"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-237g34ts
       cwd: $PIP_TEMP_DIR/pillow/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'azure-pipelines.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.azure-pipelines'
  no previously-included directories found matching '.travis'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "$PIP_TEMP_DIR/pillow/setup.py", line 852, in <module>
      setup(
    File "$VIRTUALENV/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "$PYTHON_INSTALLATION/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "$PYTHON_INSTALLATION/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "$VIRTUALENV/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "$PYTHON_INSTALLATION/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "$PYTHON_INSTALLATION/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "$PYTHON_INSTALLATION/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "$PYTHON_INSTALLATION/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "$PIP_TEMP_DIR/pillow/setup.py", line 687, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "$PIP_TEMP_DIR/pillow/setup.py", line 903, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=25ce33157ac5f32d404f80c8768c0f7be1c193ef4c2a03497600e475a8a140a7
  Stored in directory: $HOME/.cache/pip/wheels/2f/a0/d3/4030d9f80e6b3be787f19fc911b8e7aa462986a40ab1e4bb94
Successfully built numpy future
Failed to build Pillow
Installing collected packages: numpy, Pillow, six, future, fpdf2
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: $VIRTUALENV/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"'; __file__='"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6sq9ss4q/install-record.txt --single-version-externally-managed --compile --install-headers $VIRTUALENV/include/site/python3.9/Pillow
         cwd: $PIP_TEMP_DIR/pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "$PIP_TEMP_DIR/pillow/setup.py", line 852, in <module>
        setup(
      File "$VIRTUALENV/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "$PYTHON_INSTALLATION/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "$PYTHON_INSTALLATION/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "$VIRTUALENV/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "$PYTHON_INSTALLATION/distutils/command/install.py", line 590, in run
        self.run_command('build')
      File "$PYTHON_INSTALLATION/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "$PYTHON_INSTALLATION/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "$PYTHON_INSTALLATION/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "$PYTHON_INSTALLATION/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "$PYTHON_INSTALLATION/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "$PIP_TEMP_DIR/pillow/setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "$PIP_TEMP_DIR/pillow/setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: $VIRTUALENV/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"'; __file__='"'"'$PIP_TEMP_DIR/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6sq9ss4q/install-record.txt --single-version-externally-managed --compile --install-headers $VIRTUALENV/include/site/python3.9/Pillow Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '$VIRTUALENV/bin/python -m pip install --upgrade pip' command.

```

**Comment by alexanderankin** [comment]
fixed, published new version
